x=6
y=2
z=7
print(f"{x} + {y} = {x+y}")
print(f"{x} - {y} = {x-y}")
print(f"{x} x {y} = {x*y}")
print(f"{x} / {y} = {x/y}")
print(f"{x} // {y} = {x//y}")
print(f"{z} % {y} = {z%y}")
print(f"{x} ^ {y} = {x**y}")
print(f"Raíz de {36} = {36**0.5}")